### ISSUE TITLE
Missing path on Windows 10

### ISSUE THREAD

**Issue by mdmcginn** [ndom91/create-pika-app#36]
It still seems like snowpack-init would only run for me on Windows 10 if the project was already set up - if the new directory already existed, with a proper package.json. If I create a package.json for example, the error message begins to complain about its contents or lack thereof:

```
C:\Users\Michael\Documents\nginx>npx snowpack-init awesome
npx: installed 84 in 27.336s
? Please choose a template app-preact
The system cannot find the path specified.

Welcome to snowpack-init ✨

Creating app: awesome
Template: app-preact

The system cannot find the path specified.
C:\Users\Michael\AppData\Roaming\npm-cache\_npx\9848\node_modules\snowpack-init\node_modules\jsonfile\index.js:70
      throw err
      ^

Error: C:\Users\Michael\Documents\nginx/awesome/package.json: ENOENT: no such file or directory, open 'C:\Users\Michael\Documents\nginx/awesome/package.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.readFileSync (C:\Users\Michael\AppData\Roaming\npm-cache\_npx\9848\node_modules\snowpack-init\node_modules\jsonfile\index.js:64:22)
    at shell.exec (C:\Users\Michael\AppData\Roaming\npm-cache\_npx\9848\node_modules\snowpack-init\dist-node\index.js:101:33)
    at C:\Users\Michael\AppData\Roaming\npm-cache\_npx\9848\node_modules\snowpack-init\node_modules\shelljs\src\exec.js:127:9
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

C:\Users\Michael\Documents\nginx>```

**Comment by ndom91** [comment]
@mdmcginn so your saying with a proper, filled out package.json already existing it works, but if you create one, i.e. just `touch` an empty one, it does not work? 

Btw I already see the slashes are wrong in half the path in your error message.. Ill look into that.
